# --- TIPOGRAFÍA ---
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --- APARIENCIA Y TRANSPARENCIA ---
background_opacity 0.85
# Si quieres desenfoque detrás de la terminal (depende de Hyprland)
background_blur    1 

# Márgenes internos para que el texto no toque los bordes
window_padding_width 10

# Quitar el sonido molesto de la campana
enable_audio_bell no

# Estilo del cursor
cursor_shape beam