# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

# EXEC ONCE 

exec-once = waybar

# CONFIGURACIONES GENERALES

input {
    kb_layout = es,us
    kb_variant =
    kb_options = grp:win_space_toggle # Cambia entre ES y US al tocar SUPER + Espacio
    
    follow_mouse = 1
    sensitivity = 0 # -1.0 a 1.0, 0 significa sin modificación de aceleración
}

general {
    gaps_in = 3     # Menos espacio entre ventanas colindantes
    gaps_out = 6    # Menos espacio vacío en los bordes de la pantalla
    border_size = 2
    col.active_border = rgba(89b4faff) # Azul activo
    col.inactive_border = rgba(313244ff) # Gris oscuro inactivo
}

monitor=,prefered,auto,1

# VARIABLES DE AMBIENTE

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

$mainMod = SUPER
$terminal = kitty
$fileManager = $terminal --class yazi_floating -e yazi
$menu = rofi -show drun
$browser = brave

# BINDEOS

bind = $mainMod, period, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, B, exec, $browser

# MOVIMIENTO ENTRE VENTANAS

bind = $mainMod, left,  movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up,    movefocus, u
bind = $mainMod, down,  movefocus, d

# MOVIMIENTO ENTRE WORKSPACES

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4