# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

# VARIABLES DE AMBIENTE

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

$mainMod = SUPER
$terminal = kitty
$fileManager = $terminal --class yazi_floating -e yazi
$menu = rofi -show drun
$browser = brave
$fondo = /home/Narcho/Pictures/Fondos/wallpaper.jpg

# EXEC ONCE 

exec-once = waybar
exec-once = mako
exec-once = swayosd-server
exec-once = swaybg -o eDP-1 -i $fondo -m fill

# CONFIGURACIONES GENERALES

input {
    kb_layout = es,us
    kb_variant =
    kb_options = grp:win_space_toggle # Cambia entre ES y US al tocar SUPER + Espacio
    
    follow_mouse = 1
    sensitivity = 0 # -1.0 a 1.0, 0 significa sin modificación de aceleración
}
general {
    gaps_in = 3     # Menos espacio entre ventanas colindantes
    gaps_out = 6    # Menos espacio vacío en los bordes de la pantalla
    border_size = 2
    col.active_border = rgba(313244ff) # Gris oscuro inactivo
    col.inactive_border = rgba(313244cc) # Gris oscuro inactivo
}

decoration {
    active_opacity = 0.8
    inactive_opacity = 0.65
}

monitor=,prefered,auto,1

# BINDEOS

bind = $mainMod, period, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, B, exec, $browser

# MOVIMIENTO ENTRE VENTANAS

bind = $mainMod, left,  movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up,    movefocus, u
bind = $mainMod, down,  movefocus, d

# MOVIMIENTO ENTRE WORKSPACES

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4

# Bindeos Volumen

# Mutear audio (F1)
bind = , F1, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Bajar volumen (F2)
binde = , F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# Subir volumen (F3)
binde = , F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+


# Bindeos Brillo

# Brillo con Super + F12 / F11
bind = SUPER, F12, exec, brightnessctl set +10%

bind = SUPER, F11, exec, brightnessctl set 10%-
